from __future__ import annotations

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

from build_model_output_repairs import promote_counter_material_salience, validate_source_binding, validated_scores


RAW = ROOT / "experiments" / "cross_engine_model_outputs" / "raw" / "cross_engine_authority_recommendations.md"
RAW_OUT = ROOT / "experiments" / "cross_engine_model_outputs" / "scenarios"
REPAIR_OUT = ROOT / "experiments" / "cross_engine_model_repairs" / "scenarios"

ENGINES = {
    "codex-gpt55": {"provider": "openai", "model": "gpt-5.5", "capture_mode": "codex_exec_no_browse_no_tools"},
    "codex-gpt54-mini": {"provider": "openai", "model": "gpt-5.4-mini", "capture_mode": "codex_exec_no_browse_no_tools"},
    "gemini-25-pro": {"provider": "google", "model": "gemini-2.5-pro", "capture_mode": "gemini_cli_no_browse_no_tools"},
}

CLAIM_TERMS = {
    "apa-5-usc-706": "5 U.S.C. 706 section 706",
}

ISSUES = {
    "us-agency-deference": {
        "profile": "common_law",
        "manifest": "experiments/issue_gold_sets/manifests/us_agency_deference_after_loper_bright.json",
        "assumption": "united_states_federal_administrative_law",
        "high": ["loper-bright-603-us-369", "apa-5-usc-706", "skidmore-323-us-134"],
        "counter": ["skidmore-323-us-134", "kisor-588-us-558"],
        "items": [
            ("Loper Bright", "loper-bright-603-us-369", "Loper Bright"),
            ("5 U.S.C. 706", "apa-5-usc-706", "5 U.S.C. 706"),
            ("Skidmore", "skidmore-323-us-134", "Skidmore"),
            ("Kisor", "kisor-588-us-558", "Kisor"),
        ],
    },
    "uk-mesothelioma-causation": {
        "profile": "common_law",
        "manifest": "experiments/issue_gold_sets/manifests/uk_mesothelioma_causation_after_fairchild.json",
        "assumption": "england_and_wales_tort_law",
        "high": ["fairchild-2002-ukhl-22", "compensation-act-2006-s3", "sienkiewicz-2011-uksc-10"],
        "counter": ["barker-2006-ukhl-20"],
        "items": [
            ("Fairchild", "fairchild-2002-ukhl-22", "Fairchild"),
            ("Barker", "barker-2006-ukhl-20", "Barker"),
            ("Compensation Act 2006 s.3", "compensation-act-2006-s3", "Compensation Act 2006 s.3"),
            ("Sienkiewicz", "sienkiewicz-2011-uksc-10", "Sienkiewicz"),
        ],
    },
    "eu-gdpr-article15": {
        "profile": "civil_law",
        "manifest": "experiments/issue_gold_sets/manifests/eu_gdpr_article15_access_rights.json",
        "assumption": "european_union_data_protection_law",
        "high": ["gdpr-art-15", "cjeu-c-154-21-osterreichische-post", "cjeu-c-487-21-crif"],
        "counter": ["gdpr-art-15-4"],
        "items": [
            ("GDPR Article 15", "gdpr-art-15", "GDPR Article 15"),
            ("C-154/21", "cjeu-c-154-21-osterreichische-post", "C-154/21"),
            ("C-487/21", "cjeu-c-487-21-crif", "C-487/21"),
            ("GDPR Article 15(4)", "gdpr-art-15-4", "GDPR Article 15(4)"),
        ],
    },
}


def main() -> int:
    RAW_OUT.mkdir(parents=True, exist_ok=True)
    REPAIR_OUT.mkdir(parents=True, exist_ok=True)
    for directory in (RAW_OUT, REPAIR_OUT):
        for old in directory.glob("*.json"):
            old.unlink()
    raw_count = 0
    repair_count = 0
    for engine_id, engine in ENGINES.items():
        for issue_id, issue in ISSUES.items():
            scenario = _raw_scenario(engine_id, engine, issue_id, issue)
            (RAW_OUT / f"{scenario['id']}.json").write_text(
                json.dumps(scenario, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )
            raw_count += 1
            repaired = _repaired_scenario(scenario, issue)
            (REPAIR_OUT / f"{repaired['id']}.json").write_text(
                json.dumps(repaired, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )
            repair_count += 1
    print(f"Wrote {raw_count} cross-engine raw scenarios and {repair_count} source-supported repairs")
    return 0


def _raw_scenario(engine_id: str, engine: dict, issue_id: str, issue: dict) -> dict:
    scenario_id = f"cross-engine-{engine_id}-{issue_id}"
    section = f"{engine_id}--{issue_id}"
    source_ids = [item[1] for item in issue["items"]]
    return {
        "id": scenario_id,
        "claimed_status": "normative_material_screening_output",
        "jurisdiction_profile": issue["profile"],
        "deployment_context": f"Cross-engine raw authority recommendation for {issue_id} generated by {engine_id}.",
        "scores": {
            "S": {"score": 1, "evidence": "The engine named recognizable authorities, but source links remain verification-needed."},
            "Q": {"score": 2, "evidence": "Provider, model, prompt, transcript section and output identifier are recorded."},
            "H": {"score": 2, "evidence": "The output covers the issue-defined high-authority set."},
            "K": {"score": 2, "evidence": "The output includes the issue-defined limiting or counter-material set."},
            "T": {"score": 1, "evidence": "The raw output is inspectable by a reviewer, but has no party-facing contestation route."},
            "L": {"score": 1, "evidence": "The transcript is logged, but no authorized decision-maker adopted it."},
        },
        "authority_sets": {
            "high_authority": issue["high"],
            "retrieved_high_authority": [source_id for source_id in source_ids if source_id in set(issue["high"])],
            "counter_or_limiting": issue["counter"],
            "retrieved_counter_or_limiting": [source_id for source_id in source_ids if source_id in set(issue["counter"])],
            "invalid_or_superseded": [],
            "retrieved": source_ids,
        },
        "upstream_metrics": {"precision": 1.0, "recall": 1.0, "f1": 1.0},
        "upstream_output": {
            "provider": engine["provider"],
            "model": engine["model"],
            "capture_mode": engine["capture_mode"],
            "raw_file": f"experiments/cross_engine_model_outputs/raw/cross_engine_authority_recommendations.md#{section}",
        },
        "evidence_packet": {
            "source_collection": "raw cross-engine model output; citations require independent verification",
            "output_units": [
                {
                    "id": f"unit-{index}",
                    "claim": f"{CLAIM_TERMS.get(source_id, label)} is presented as a material for legal review.",
                    "source_ids": [source_id],
                    "locators": [locator],
                }
                for index, (label, source_id, locator) in enumerate(issue["items"], start=1)
            ],
            "output_links": [
                {
                    "unit_id": f"unit-{index}",
                    "source_id": source_id,
                    "locator": locator,
                    "supports_claim": True,
                    "source_tag": "needs_verification",
                }
                for index, (_, source_id, locator) in enumerate(issue["items"], start=1)
            ],
        },
        "review_gate": {
            "attorney_review_required": True,
            "review_status": "pending",
            "reliance_gate": "internal_research",
            "jurisdiction_assumptions": [issue["assumption"]],
            "irreversible_action": False,
            "human_authorization": False,
        },
        "failure_flags": [],
        "expected_allowed_status": "reference_information",
        "expected_disposition": "suspension" if issue_id == "eu-gdpr-article15" else "downgrade",
    }


def _repaired_scenario(scenario: dict, issue: dict) -> dict:
    repaired = json.loads(json.dumps(scenario))
    repaired["id"] = "source-bound-" + scenario["id"]
    repaired["deployment_context"] = scenario["deployment_context"] + " Source-supported repair variant."
    repaired["system_role"] = "auditable_procedural_tool"
    repaired["evidence_packet"]["source_collection"] = issue["manifest"]
    validation = validate_source_binding(repaired, ROOT / issue["manifest"])
    if validation["all_links_source_bound"]:
        for link in repaired["evidence_packet"].get("output_links", []):
            link["source_tag"] = "tool_verified"
            key = f"{link.get('unit_id')}::{link.get('source_id')}"
            evidence = validation["source_support_by_link"].get(key, [])
            link["support_label"] = "supports"
            link["validated_source_support"] = evidence
            link["validated_support_terms"] = sorted({term for item in evidence for term in item.get("matched_terms", [])})
        validation["source_tag_assignment"] = "assigned_after_manifest_locator_issue_set_and_source_support_validation"
        validation["assigned_procedural_source_tags"] = validation["output_links"]
    else:
        validation["source_tag_assignment"] = "not_assigned_validation_failed"
        validation["assigned_procedural_source_tags"] = 0
    repaired["source_binding_validation"] = validation
    repaired["scores"] = validated_scores(repaired, validation)
    repaired["review_gate"] = {
        "attorney_review_required": True,
        "review_status": "completed",
        "reliance_gate": "attorney_review",
        "jurisdiction_assumptions": [issue["assumption"]],
        "contestability_channel": "cross-engine-source-bound-review-record",
        "irreversible_action": False,
        "human_authorization": False,
    }
    if validation["all_links_source_bound"]:
        promote_counter_material_salience(repaired)
        repaired["expected_allowed_status"] = "normative_material_screening_output"
        repaired["expected_disposition"] = "none"
    return repaired


if __name__ == "__main__":
    raise SystemExit(main())
